// <auto-generated />
namespace TradeIdeasNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users));
        
        string IMigrationMetadata.Id
        {
            get { return "201904172251199_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
